version: "3.7"

services:
  NginxProxyManager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ${CONFIG_FOLDER}/${CONTAINER_NAME}/data:/data
      - ${CONFIG_FOLDER}/${CONTAINER_NAME}/letsencrypt:/etc/letsencrypt
