services:
  NginxProxyManager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: NginxProxyManager
    restart: unless-stopped
    ports:
      - '${NPM_HTTP_PORT}:80'
      - '${NPM_PORTAL_PORT}:81' 
      - '${NPM_HTTPS_PORT}:443'
    volumes:
      - ${CONFIG_FOLDER}/NginxProxyManager/data:/data
      - ${CONFIG_FOLDER}/NginxProxyManager/letsencrypt:/etc/letsencrypt
