version: "3.7"

services:
  NginxProxyManager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: NginxProxyManager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
