version: "3.7"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_FOLDER}/sonarr:/config
      - ${SERIES_FOLDER}:/tvseries
      - ${DATA_FOLDER}:/data
    ports:
      - 8989:8989
    restart: unless-stopped
