services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    ports:
      - 8989:8989
    volumes:
      - ${CONFIG_FOLDER}/sonarr:/config
      - ${DATA_FOLDER}:/data
    restart: unless-stopped