services:
  wyoming-piper:
    image: rhasspy/wyoming-piper:latest
    container_name: wyoming-piper
    command: >
      --voice nl_NL-alex-medium
    ports:
      - "10200:10200"
    volumes:
      - ${CONFIG_FOLDER}/piper:/data
    restart: unless-stopped
