services:
  wyoming-piper:
    image: rhasspy/wyoming-piper:latest
    container_name: wyoming-piper
    dns:
      - 1.1.1.1
      - 8.8.8.8
    command: 
      - "--voice"
      - "alex"
      - "--data-dir"
      - "/data"
      - "--download-dir"
      - "/data/download"
    ports:
      - "10200:10200"
    volumes:
      - ${CONFIG_FOLDER}/piper:/data
    restart: unless-stopped