services:
  gluetun_nzbdav:
    image: qmcgaw/gluetun
    container_name: gluetun_nzbdav
    hostname: gluetun_nzbdav
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - ${NZBDAV_PORT}:3000
    volumes:
      - ${CONFIG_FOLDER}/gluetun_nzbdav:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${NZBDAV_WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${NZBDAV_WIREGUARD_ADDRESSES}
      - SERVER_CITIES=Amsterdam
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - DNS_UPDATE=yes
    restart: unless-stopped

  nzbdav:
    image: nzbdav/nzbdav:latest
    container_name: nzbdav
    restart: unless-stopped
    network_mode: "container:gluetun_nzbdav"
    depends_on:
      - gluetun_nzbdav
    healthcheck:
      test: curl -f http://localhost:3000/health || exit 1
      # Check every 1 minute
      interval: 1m
      # If it fails 3 times (3 minutes total), restart it
      retries: 3
      # Give it 5 seconds to boot up
      start_period: 5s
      # If it doesn't answer in 5 seconds, assume it's frozen
      timeout: 5s
    environment:
      # Change these IDs to match your Docker user that you got from above
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/nzbdav:/config
      - ${DATA_FOLDER}:/data