services:
  nzbdav:
    image: nzbdav/nzbdav:latest
    container_name: nzbdav
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:3000/health || exit 1
      # Check every 1 minute
      interval: 1m
      # If it fails 3 times (3 minutes total), restart it
      retries: 3
      # Give it 5 seconds to boot up
      start_period: 5s
      # If it doesn't answer in 5 seconds, assume it's frozen
      timeout: 5s
    ports:
      - ${NZBDAV_PORT}:3000
    dns:
      - 1.1.1.1 # force cloudflare DNS
      - 8.8.8.8 # force google DNS
    environment:
      # Change these IDs to match your Docker user that you got from above
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/nzbdav:/config
      - ${DATA_FOLDER}:/mnt/data

  nzbdav_rclone:
    image: rclone/rclone:latest
    container_name: nzbdav_rclone
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      # Host Path : Container Path : Propagation
      - ${DATA_FOLDER}:/mnt/data:rshared
      - ${CONFIG_FOLDER}/nzbdav/rclone.conf:/config/rclone/rclone.conf
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse:rwm
    depends_on:
      nzbdav:
        condition: service_healthy
        restart: true
    # Optimized mounting flags for streaming
    # 0M buffer size prevents double-caching (Kernel + RClone)
    # 512M read-ahead ensures smooth playback
    command: >
      mount nzbdav: /mnt/remote/nzbdav
        --uid=${PUID}
        --gid=${PGID}
        --allow-other
        --links
        --use-cookies
        --vfs-cache-mode=full
        --vfs-cache-max-size=20G
        --vfs-cache-max-age=24h
        --buffer-size=0M
        --vfs-read-ahead=512M
        --dir-cache-time=20s