services:
  wallos:
    container_name: ${CONTAINER_NAME}
    image: bellamy/wallos:latest
    ports:
      - ${WALLOS_PORT}:80
    env_file: 
      - ../.env
      - .env
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/wallos/db:/var/www/html/db
      - ${CONFIG_FOLDER}/wallos/logos:/var/www/html/images/uploads/logos
    restart: unless-stopped
