services:
  wallos:
    container_name: ${CONTAINER_NAME}
    image: bellamy/wallos:latest
    ports:
      - "8282:80"
    env_file:
      - wallos.env
    environment:
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/${CONTAINER_NAME}/db:/var/www/html/db
      - ${CONFIG_FOLDER}/${CONTAINER_NAME}/logos:/var/www/html/images/uploads/logos
    restart: unless-stopped
