version: "3.7"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1111
      - PGID=4321
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - $CONFIG_FOLDER/radarr:/config
      - $MOVIE_FOLDER:/movies #Aanpassen
      - $DOWNLOAD_FOLDER:/downloads #Aanpassen
    ports:
      - 7878:7878
    restart: unless-stopped
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=2222
      - PGID=4321
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - $CONFIG_FOLDER/sonarr:/config
      - $SERIES_FOLDER:/tvseries #Aanpassen
      - $DOWNLOAD_FOLDER:/downloads #Aanpassen
    ports:
      - 8989:8989
    restart: unless-stopped
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - PUID=3333
      - PGID=4321
      - TZ=Etc/UTC
      - UMASK=002
      - WEBUI_PORT=8080
    volumes:
      - $CONFIG_FOLDER/qbit:/config
      - $DOWNLOAD_FOLDER:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=4444
      - PGID=4321
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - $CONFIG_FOLDER/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    logging:
     driver: json-file
     #options:
      # max-file: 3
      # max-size: 50
    user: 8888:8888
    environment:
      - TZ=Etc/UTC
      #- AUTOBRR__DATABASE_TYPE=sqlite
      - AUTOBRR__HOST=0.0.0.0
      #- AUTOBRR__PORT=7474
    volumes:
      - $CONFIG_FOLDER/autobrr/config:/config
    ports:
      - 7474:7474
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=5555
      - PGID=4321
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - $CONFIG_FOLDER/bazarr:/config
      - $MOVIE_FOLDER:/movies #Aanpassen
      - $SERIES_FOLDER:/tvseries #Aanpassen
    ports:
      - 6767:6767
    restart: unless-stopped

  mkvtoolnix:
    image: jlesage/mkvtoolnix
    container_name: mkvtoolnix
    ports:
      - 5800:5800
    volumes:
      - $CONFIG_FOLDER/mkvtoolnix:/config:rw
      - $MOVIE_FOLDER:/storage:rw

  openbooks:
    container_name: OpenBooks
    image: evanbuss/openbooks:latest
    restart: unless-stopped
    ports:
      - 7676:80
    volumes:
      - $BOOK_FOLDER:/books
    command: --persist --name Carnita1234

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - $CONFIG_FOLDER/homarr/configs:/app/data/configs
      - $CONFIG_FOLDER/homarr/icons:/app/public/icons
      - $CONFIG_FOLDER/homarr/data:/data
    ports:
      - 7575:7575

  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.0.0 # 
    container_name: mealie
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=192.168.2.13
      - DEFAULT_GROUP=Home
      - DEFAULT_EMAIL=christiaanvdlaken@gmail.com
    restart: always

  ##
  # Los deployen zodat ik vanuit portainer de compose file via GIT kan uploaden als een stack
  ##
  # portainer:
  #     container_name: portainer
  #     image: portainer/portainer-ce:latest
  #     ports:
  #       - 9443:9443
  #     volumes:
  #         - $CONFIG_FOLDER/portainer:/data
  #         - /var/run/docker.sock:/var/run/docker.sock
  #     restart: unless-stopped

  flaresolverr:
      # DockerHub mirror flaresolverr/flaresolverr:latest
      image: ghcr.io/flaresolverr/flaresolverr:latest
      container_name: flaresolverr
      environment:
        - LOG_LEVEL=${LOG_LEVEL:-info}
        - LOG_HTML=${LOG_HTML:-false}
        - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
        - TZ=Europe/London
      ports:
        - "${PORT:-8191}:8191"
      restart: unless-stopped     

volumes:
  mealie-data:
    driver: local
