services:
  movie-roulette:
    image: sahara101/movie-roulette:latest
    container_name: movie-roulette
    ports:
      - "${MOVIE_ROULETTE_PORT}:4000"
    volumes:
      - ${CONFIG_FOLDER}/movie_roulette:/app/data
    restart: unless-stopped
    networks:
      - docker_net

networks:
  docker_net:
    external: true