services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: ${CONTAINER_NAME}
    env_file: 
      - ../.env
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/${CONTAINER_NAME}:/config
      - ${DATA_FOLDER}/selfmark-book-downloader:/cwa-book-ingest
      - ${DATA_FOLDER}/media/books:/calibre-library
    ports:
      - ${PORT}:8083
    restart: unless-stopped
