services:
  speech-to-phrase:
    image: rhasspy/wyoming-speech-to-phrase:latest
    container_name: speech-to-phrase
    restart: unless-stopped
    dns:
      - 1.1.1.1 # force cloudflare DNS
      - 8.8.8.8 # force google DNS
    ports:
      - "10301:10300"
    volumes:
      - ${CONFIG_FOLDER}/speech_to_phrase/models:/models
      - ${CONFIG_FOLDER}/speech_to_phrase/train:/train
    environment:
      - TZ=${TZ}
    command: >
      --hass-websocket-uri ws://${HASSS_URL}:8123/api/websocket
      --hass-token ${LLAT_STP}
      --retrain-on-start