services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    ports:
      - "${OPENWEBUI_PORT}:8080"
    volumes:
      - ${CONFIG_FOLDER}/openwebui:/app/backend/data

