services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:8080"
    volumes:
      - ${CONFIG_FOLDER}/${CONTAINER_NAME}:/app/backend/data
    env_file: 
      - ../.env
      - .env
volumes:
  open-webui: