services:
  shelfmark:
    image: ghcr.io/calibrain/shelfmark:latest
    container_name: ${CONTAINER_NAME}
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    env_file: 
      - ../.env
      - .env
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      - ${DATA_FOLDER}/media/books:/books # Default destination for book downloads
      - ${CONFIG_FOLDER}/${CONTAINER_NAME}:/config # App configuration
      # Required for torrent / usenet - path must match your download client's volume exactly
      - ${DATA_FOLDER}/${CONTAINER_NAME}:/path/to/downloads