services:
  shelfmark:
    image: ghcr.io/calibrain/shelfmark:latest
    container_name: shelfmark
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    ports:
      - ${SHELFMARK_PORT}:8084
    restart: unless-stopped
    volumes:
      - ${DATA_FOLDER}/media/books:/books # Default destination for book downloads
      - ${CONFIG_FOLDER}/shelfmark:/config # App configuration
      # Required for torrent / usenet - path must match your download client's volume exactly
      - ${DATA_FOLDER}/usenet/downloads/books:/usenet_books # usenet download location