services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/sabnzbd:/config
      - ${DATA_FOLDER}/usenet:/data/usenet:rw
    ports:
      - "${SABNZBD_PORT}:8080"
    restart: unless-stopped
