version: "3.7"

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: ${CONTAINER_NAME}
    env_file: ../.env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/${CONTAINER_NAME}:/config
      - ${DATA_FOLDER}/usenet:/data/usenet:rw
    ports:
      - 8282:8080
    restart: unless-stopped
