services:
  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    dns:
      - 1.1.1.1 # force cloudflare DNS
      - 8.8.8.8 # force google DNS    
    ports:
      - ${DONETICK_PORT}:2021
    volumes:
      - ${CONFIG_FOLDER}/donetick/data:/donetick-data
      - ${CONFIG_FOLDER}/donetick/config:/config
    environment:
      - DT_ENV=selfhosted      
      - DT_DB_TYPE=sqlite      
      - DT_SQLITE_PATH=/donetick-data/donetick.db
      - TZ=${TZ}
      - DT_JWT_SECRET=${DT_JWT_SECRET_DONETICK}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:2021/api/v1/health || exit 1
      start_period: 1m
      timeout: 5s
      interval: 1m
      retries: 3
      