services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    container_name: paperless_broker
    volumes:
      - ${CONFIG_FOLDER}/paperless/redisdata:/data

  db:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    container_name: paperless_db
    volumes:
      - ${CONFIG_FOLDER}/paperless/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "${PAPERLESS_PORT}:8000"
    volumes:
      - ${CONFIG_FOLDER}/paperless/:/usr/src/paperless/data
      - ${NAS_FOLDER}/paperless:/usr/src/paperless/media
      - ${CONFIG_FOLDER}/paperless/export:/usr/src/paperless/export
      - ${CONFIG_FOLDER}/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
