services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${WEBUI_PORT_QBIT}:${WEBUI_PORT_QBIT}" # qbittorrent
      - "6881:6881" # qbittorrent
      - "6881:6881/udp" # qbittorrent
      - "${SABNZBD_PORT}:${SABNZBD_PORT}"   # sabnzbd
      - "8000:8000"   # Gluetun status API
      - "${SHELFMARK_PORT}:${SHELFMARK_PORT}"   # shelfmark
    volumes:
      - ${CONFIG_FOLDER}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=Amsterdam
      - DNS_UPDATE=yes

   qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    network_mode: "service:gluetun"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WEBUI_PORT=${WEBUI_PORT_QBIT}
    volumes:
      - ${CONFIG_FOLDER}/qbittorrent:/config
      - ${DATA_FOLDER}/torrents:/data/torrents:rw
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/sabnzbd:/config
      - ${DATA_FOLDER}/usenet:/data/usenet:rw
    restart: unless-stopped
  
  shelfmark:
    image: ghcr.io/calibrain/shelfmark:latest
    container_name: shelfmark
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    restart: unless-stopped
    volumes:
      - ${DATA_FOLDER}/media/books:/books # Default destination for book downloads
      - ${CONFIG_FOLDER}/shelfmark:/config # App configuration
      # Required for torrent / usenet - path must match your download client's volume exactly
      - ${DATA_FOLDER}/usenet/downloads/books:/usenet_books # usenet download location
