services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "8180:8080" # qbittorrent
      - "6881:6881" # qbittorrent
      - "6881:6881/udp" # qbittorrent
      - "8080:8080"   # sabnzbd
      - "8000:8000"   # Gluetun status API
    volumes:
      - ${CONFIG_FOLDER}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=Amsterdam
      - DNS_UPDATE=yes

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    network_mode: "service:gluetun"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WEBUI_PORT=${WEBUI_PORT_QBIT}
    volumes:
      - ${CONFIG_FOLDER}/qbittorrent:/config
      - ${DATA_FOLDER}/torrents:/data/torrents:rw
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/sabnzbd:/config
      - ${DATA_FOLDER}/usenet:/data/usenet:rw
    restart: unless-stopped
