services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - media_net
    ports:
      - "${WEBUI_PORT_QBIT}:${WEBUI_PORT_QBIT}"
      - "6881:6881"
      - "6881:6881/udp"
      - "${SABNZBD_PORT}:${SABNZBD_PORT}"
      - "${PROWLARR_PORT}:${PROWLARR_PORT}"
      - "${NZBDAV_PORT}:3000"
      - "8000:8000"
    volumes:
      - ${CONFIG_FOLDER}/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=Amsterdam
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
      - DNS_UPDATE=yes
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    network_mode: "container:gluetun"
    depends_on:
      - gluetun
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WEBUI_PORT=${WEBUI_PORT_QBIT}
    volumes:
      - ${CONFIG_FOLDER}/qbittorrent:/config
      - ${DATA_FOLDER}/torrents:/data/torrents:rw
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "container:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/sabnzbd:/config
      - ${DATA_FOLDER}/usenet:/data/usenet:rw
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "container:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_FOLDER}/prowlarr:/config
      - ${DATA_FOLDER}:/data
    restart: unless-stopped

  nzbdav:
      image: nzbdav/nzbdav:latest
      container_name: nzbdav
      restart: unless-stopped
      network_mode: "container:gluetun"
      depends_on:
        - gluetun
      healthcheck:
        test: curl -f http://localhost:3000/health || exit 1
        # Check every 1 minute
        interval: 1m
        # If it fails 3 times (3 minutes total), restart it
        retries: 3
        # Give it 5 seconds to boot up
        start_period: 5s
        # If it doesn't answer in 5 seconds, assume it's frozen
        timeout: 5s
      environment:
        # Change these IDs to match your Docker user that you got from above
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - ${CONFIG_FOLDER}/nzbdav:/config
        - ${DATA_FOLDER}:/data

networks:
  media_net:
    external: true