services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    container_name: nextcloud-aio-mastercontainer
    restart: always
    ports:
      - "8438:8080"
    environment:
      - APACHE_PORT=11000
      # Waar de gebruikersdata van nextcloud opgeslagen wordt
      - NEXTCLOUD_DATADIR=${NAS_FOLDER}/nextcloud/data
    volumes:
      # De configuratie van de mastercontainer zelf
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer