version: "3.7"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: ${CONTAINER_NAME}
    env_file: 
      - ../.env
      - .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_FOLDER}/${CONTAINER_NAME}:/config
      - ${DATA_FOLDER}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
