version: "3.7"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - ${CONFIG_FOLDER}/radarr:/config
      - ${MOVIE_FOLDER}:/movies
      - ${DOCU_FOLDER}:/documentaries
      - ${DATA_FOLDER}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
