services:
  wyoming-whisper:
    image: ghcr.io/sjtrny/wyoming-whisper-intel:release # specifieke image met optimalisaties voor Intel iGPU's
    container_name: wyoming-whisper
    restart: unless-stopped
    environment:
      # Gebruik de iGPU voor acceleratie (OpenVINO/oneAPI)
      - ONEAPI_DEVICE_SELECTOR=level_zero:gpu
      # Optimaliseer threading voor een i7 (instellen op aantal fysieke cores, meestal 4 of 6)
      - OMP_NUM_THREADS=4
    devices:
      # Geeft de container direct toegang tot de Intel GPU hardware
        - /dev/dri:/dev/dri
    group_add:
      - "992" # Voeg de gebruiker toe aan de 'video' groep (ID 992) voor toegang tot de GPU
    dns:
      - 1.1.1.1 # force cloudflare DNS
      - 8.8.8.8 # force google DNS
    ports:
      - "10300:10300"
    volumes:
      - ${CONFIG_FOLDER}/whisper:/data
    command: [
      "--model", "large-v3-turbo", 
      "--language", "nl", 
      "--beam-size", "2", # pakt {beam-size} mogelijkheden, en kiest de meestwaarschijlijke. Hoe hoger hoe beter, maar ook trager.
      "--data-dir", "/data"
    ]
