services:
  web:
    image: haedlessdev/portnote:latest
    restart: always
    ports:
      - "${PORTNOTE_PORT}:3000"
    environment:
      JWT_SECRET: ${PORTNOTE_JWT_SECRET}
      USER_SECRET: ${PORTNOTE_USER_SECRET}
      LOGIN_USERNAME: ${PORTNOTE_LOGIN_USERNAME}
      LOGIN_PASSWORD: ${PORTNOTE_LOGIN_PASSWORD} 
      DATABASE_URL: ${PORTNOTE_DATABASE_URL}
    depends_on:
      db:
        condition: service_started

  agent:
    image: haedlessdev/portnote-agent:latest
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres"
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ${CONFIG_FOLDER}/portnote/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: