services:
  swiparr:
    image: ghcr.io/m3sserstudi0s/swiparr:latest
    container_name: swiparr
    restart: unless-stopped
    environment:
      - JELLYFIN_URL=${BASE_URL}:{JELLYFIN_PORT}
      # - JELLYFIN_PUBLIC_URL=https://jellyfin.yourdomain.com
    volumes:
      - ${CONFIG_FOLDER}/swiparr/swiparr-data:/app/data
    ports:
      - ${SWIPARR_PORT}:4321