services:
  profilarr:
    image: santiagosayshey/profilarr:lates
    container_name: profilarr
    networks:
      - media_net
    dns:
      - 1.1.1.1 # force cloudflare DNS
      - 8.8.8.8 # force google DNS
    ports:
      - "${PROFILARR_PORT}:6868"
    volumes:
      - ${CONFIG_FOLDER}/profilarr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PARSER_HOST=parser
      - PARSER_PORT=5000
    depends_on:
      parser:
        condition: service_healthy

# Media netwerk zodat alles in hetzelfde netwerk zit en de containers elkaar kunnen vinden
networks:
  media_net:
    external: true