services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: ${CONTAINER_NAME}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    env_file: 
      - ../.env
      - .env
    ports:
      - "8180:8080" # qbittorrent
      - "8989:8989" # Sonarr
      - "9696:9696" # Prowlarr
    volumes:
      - ${CONFIG_FOLDER}/${CONTAINER_NAME}:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=WFUvjnjrGxdpHzeQRNwBvARoe//AUomaqBWjdR6p9hk=
      - WIREGUARD_ADDRESSES=10.67.82.91/32
      - SERVER_CITIES=Amsterdam