services:
  wyoming-stt-nemo:
    image: ghcr.io/tboby/wyoming-onnx-asr:latest
    container_name: wyoming-stt-nemo
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - "10301:10300"  # Poort 10301 zodat hij netjes naast je Whisper container kan draaien
    volumes:
      - ${CONFIG_FOLDER}/nemo:/data
    command:
      - --uri
      - "tcp://0.0.0.0:10300"
      - --model-multilingual
      - "nemo-parakeet-tdt-0.6b-v3"
      - --model-dir
      - "/data"
      - --device
      - "cpu"          # Dwingt CPU-berekening af, net als je Whisper setup