services:
  qui:
    image: ghcr.io/autobrr/qui:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env    
    ports:
      - "7476:7476"
    volumes:
      - ${CONFIG_FOLDER}/${CONTAINER_NAME}:/config
    #environment: